name: Java CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verifica file enhancer.xml
        run: |
          ls -la openjpa-persistence-locking/src/test/ant/
          cat openjpa-persistence-locking/src/test/ant/enhancer.xml

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.
        with:
          java-version: 8
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: mvn clean install -P jdk8,evosuite -DskipTests

